### ISSUE TITLE
Externals scripts/styles are not being injected into the index.html

### ISSUE THREAD

**Issue by agubler** [dojo/webpack-contrib#119]
**Bug**

The external resource that need to be injected into the index.html are not being included as expected.

**Comment by mwistrand** [comment]
The underlying problem is that the `HtmlWebpackIncludeAssetPlugin` instantiated by the externals loader plugin expects to be registered after the `HtmlWebpackPlugin`, but `@dojo/cli-build-app` instantiates `HtmlWebpackPlugin` _after_ the `ExternalsLoaderPlugin`.
