### ISSUE TITLE
Support jsdom as a Build Time Renderer

### ISSUE THREAD

**Issue by matt-gadd** [dojo/webpack-contrib#197]
**Enhancement**
Rendering many pages using Puppeteer can be very slow. We should consider trying jsdom to speed this up and offering it as an alternative or default renderer. To implement we might want to write a small api wrapper around jsdom that matches puppeteer to make the implementation tidier.

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/webpack-contrib/pull/211
