### ISSUE TITLE
Migrate from Plugin to Loader

### ISSUE THREAD

**Issue by kitsonk** [dojo/webpack-contrib#2]
@kitsonk commented on [Fri Sep 29 2017](https://github.com/dojo/static-optimize-plugin/issues/3)

**Enhancement**

The architecture of `static-optimize-plugin` is limited in being a plugin.  In particular webpack does not provide easy ways for plugins to elide dependencies and update a dependency graph.  The only effective way to remove dependencies is remove them from the source as webpack loads the module.  This means that the features really should be a loader instead of a plugin.

@matt-gadd's [umd-compat-loader](https://github.com/matt-gadd/umd-compat-loader/blob/master/index.js) provides an example of loading a module, doing an AST transform on the module which also updates the source map, as a webpack loader.  We should follow a similar architecture for the features in this package.

**Comment by maier49** [comment]
Resolved by #4
