### ISSUE TITLE
BTR watch build hangs on changes after initial build

### ISSUE THREAD

**Issue by KaneFreeman** [dojo/webpack-contrib#239]
**Bug** 

BTR watch build hangs on changes after initial build.

Package Version: `alpha.1` and `alpha.7`

**Code**

- https://github.com/KaneFreeman/site/tree/upgrade
- https://github.com/dojo/site

**Expected behavior:**

App should be rebuilt in a reasonable amount of time.

**Actual behavior:**

Build process just spins on `building` without ever finishing the rebuilt.
![image](https://user-images.githubusercontent.com/1388138/72750249-4fe2a300-3b8a-11ea-9068-c4d07655b13e.png)

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/webpack-contrib/pull/237
