### ISSUE TITLE
Bug: CSS modules in entry break watch

### ISSUE THREAD

**Issue by mwistrand** [dojo/webpack-contrib#29]
**Bug**

When running webpack in watch mode with the `css-module-dts-loader`, changes to an entry point trigger a rebuild, but the entry itself is not recompiled if it imports a CSS module. If I change `import * as css from './main.css'` to `const css = require('./main.css')`, or if I comment out the usage of `css-module-dts-loader` for TypeScript files in the webpack config, then changes are correctly reflected in the output.

**Code**

```
// src/main.ts
import * as css from './main.css';

console.log(css);
```

Run a build in watch mode (e.g., with `cli-build-app`: `dojo build -w -m dev`), and then make a change to the file. For example, change to:

```
// src/main.ts
import * as css from './main.css';

console.log('Update!', css);
```

**Expected behavior:**

The change should be reflected in the output build (or in the browser if using the `webpack-dev-server`).

**Actual behavior:**

The rebuild is logged to the console, but no change is reflected in the output.

**Comment by matt-gadd** [comment]
closing for same reasons as: https://github.com/dojo/webpack-contrib/pull/30
