### ISSUE TITLE
Acorn upgrade causing dynamic import syntax error in async.js

### ISSUE THREAD

**Issue by KaneFreeman** [dojo/webpack-contrib#339]
**Bug**

`SyntaxError: Unexpected token (8:17)` occurs in [`bootstrap-plugin/async.js`](https://github.com/dojo/webpack-contrib/blob/master/src/bootstrap-plugin/async.js#L8) when building Dojo Site against version 8. Acorn version 6.2 added support for dynamic imports which is conflicting syntax wise with the dynamic import plugin used in [`static-build-loader/loader.js`](https://github.com/dojo/webpack-contrib/blob/master/src/static-build-loader/loader.ts#L145).

Acorn was updated from `6.1.1`  to `7.4.1` in #319, dynamic imports were introduced in `6.2.0`.

**Code**

https://github.com/dojo/site/tree/feature/version-8

**Comment by agubler** [comment]
Hey @KaneFreeman this was back ported so it would be broken in version 7 if this is cause of the error?

**Comment by KaneFreeman** [comment]
@agubler I would assume so, but that change to 7 was never pushed to npm.

**Comment by KaneFreeman** [comment]
@agubler yes, you are correct. it looks like dojo site is still on `cli-build-app` version `7.0.4`. Thus why it can still build in its current state.

**Comment by KaneFreeman** [comment]
Indeed, updating to `7.0.5` causes the same error to appear.
